### ISSUE TITLE
Github makes it impossible to DM people, sorry.

### ISSUE THREAD

**Issue by NameTrillion** [FallDownTheSystem/chess-vision#2]
@FallDownTheSystem

Hey I have a cloned version of a certain similar project to this that you built a while ago. I was trying to figure how to get pages to connect on certain sites as it seems they have been changed in some fashion.  I was looking over the extension script and I can't figure out why the websocket is only working for some sites other than maybe the way the other sites are restricting the CSP?  Anyway if you want to take the time to let me know why I can't figure out how to put the square block into the square hole I would greatly appreciate it lol.

**Comment by FallDownTheSystem** [comment]
Yeah those are just dom query selectors. The sites have updated so the HTML no longer matches the selector, meaning they need to be updated. It's easy enough just by inspecting the HTML.

movesSelector is used to check if the page has a chess game with moves that can be read, sanSelector is the selector for the actual moves (chess notation), overlay is the board, analysis is for checking whether an analysis board is open, sideFinder is just a function for checking if you're white or black.
